name: SoftEtherClient
options:
  bundleIdPrefix: com.leadconcept
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
targets:
  SoftEtherClient:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sources/App]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.leadconcept.SoftEtherClient

  PacketTunnel:
    type: app-extension
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Sources/PacketTunnel]
    info:
      path: Sources/PacketTunnel/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.leadconcept.SoftEtherClient.PacketTunnel
