name: VPNProject
options:
  bundleIdPrefix: com.leadconcept
targets:
  VPNApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/App]
    entitlements:
      'com.apple.security.network.client': true
      'com.apple.security.network.server': true
      'com.apple.security.application-groups': ['group.com.leadconcept.vpn']
    dependencies:
      - framework: Frameworks/SoftEtherClient.xcframework
      - target: VPNTunnel

  VPNTunnel:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/Tunnel]
    entitlements:
      'com.apple.security.network.client': true
      'com.apple.security.network.server': true
      'com.apple.security.application-groups': ['group.com.leadconcept.vpn']
      'com.apple.developer.networking.vpn.api': [allow-vpn]
    info:
      NSExtension:
        NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
        NSExtensionPrincipalClass: PacketTunnelProvider